const SESSION_DAYS=30;const MAX_IMAGE=5*1024*1024;
export default{async fetch(request,env){try{return await handle(request,env)}catch(error){console.error(error);return json({error:'Erro interno. Tente novamente.'},500)}}};
async function handle(request,env){const url=new URL(request.url);if(url.pathname.startsWith('/media/'))return serveMedia(url,env);if(url.pathname.startsWith('/api/'))return apiRoute(request,env,url);const response=await env.ASSETS.fetch(request);return harden(response)}
async function apiRoute(request,env,url){const p=url.pathname,m=request.method;if(p==='/api/catalog'&&m==='GET')return catalog(env,url);if(p==='/api/auth/register'&&m==='POST')return register(request,env);if(p==='/api/auth/login'&&m==='POST')return login(request,env);if(p==='/api/auth/logout'&&m==='POST')return logout(request,env);if(p==='/api/auth/me'&&m==='GET')return me(request,env);if(p==='/api/auth/change-password'&&m==='POST')return changePassword(request,env);if(p==='/api/auth/recovery-request'&&m==='POST')return recoveryRequest(request,env);if(p==='/api/listings'&&m==='POST')return createListing(request,env);if(p==='/api/businesses'&&m==='POST')return createBusiness(request,env);if(p==='/api/me/summary'&&m==='GET')return mySummary(request,env);if(p==='/api/me/listings'&&m==='GET')return myListings(request,env);if(p==='/api/me/businesses'&&m==='GET')return myBusinesses(request,env);if(p==='/api/favorites'&&m==='GET')return favorites(request,env);if(p==='/api/favorites'&&m==='POST')return toggleFavorite(request,env);if(p==='/api/admin/pending'&&m==='GET')return adminPending(request,env);if(p==='/api/admin/moderate'&&m==='POST')return adminModerate(request,env);if(p==='/api/admin/recovery/reset'&&m==='POST')return adminRecoveryReset(request,env);return json({error:'Rota não encontrada.'},404)}
function json(data,status=200,headers={}){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...securityHeaders(),...headers}})}
function securityHeaders(){return{'x-content-type-options':'nosniff','x-frame-options':'DENY','referrer-policy':'strict-origin-when-cross-origin','permissions-policy':'camera=(), microphone=(), geolocation=()','strict-transport-security':'max-age=31536000; includeSubDomains','content-security-policy':"default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data: blob: https://images.unsplash.com; connect-src 'self'; font-src 'self'; frame-ancestors 'none'; base-uri 'self'; object-src 'none'"}}
function harden(response){const h=new Headers(response.headers);for(const[k,v]of Object.entries(securityHeaders()))h.set(k,v);return new Response(response.body,{status:response.status,statusText:response.statusText,headers:h})}
function cleanText(v,max){return String(v??'').trim().replace(/[\u0000-\u001F\u007F]/g,' ').slice(0,max)}
function normalizePhone(v){let d=String(v??'').replace(/\D/g,'');if(d.length===10||d.length===11)d='55'+d;if(!/^55\d{10,11}$/.test(d))throw new Error('Informe um WhatsApp válido com DDD.');return d}
function validatePassword(v){const s=String(v??'');if(s.length<8||s.length>72)throw new Error('A senha precisa ter entre 8 e 72 caracteres.');return s}
async function bodyJson(request){try{return await request.json()}catch{throw new Error('Dados inválidos.')}}
function bytesToB64(bytes){let s='';for(const b of bytes)s+=String.fromCharCode(b);return btoa(s)}
function b64ToBytes(v){const s=atob(v);return Uint8Array.from(s,c=>c.charCodeAt(0))}
async function sha256(text){const buf=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text));return [...new Uint8Array(buf)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function hashPassword(password,saltB64=null){const salt=saltB64?b64ToBytes(saltB64):crypto.getRandomValues(new Uint8Array(16));const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt,iterations:100000},key,256);return{salt:bytesToB64(salt),hash:bytesToB64(new Uint8Array(bits))}}
async function verifyPassword(password,salt,expected){const result=await hashPassword(password,salt);return timingSafe(result.hash,expected)}
function timingSafe(a,b){if(a.length!==b.length)return false;let x=0;for(let i=0;i<a.length;i++)x|=a.charCodeAt(i)^b.charCodeAt(i);return x===0}
function randomToken(bytes=32){const a=crypto.getRandomValues(new Uint8Array(bytes));return [...a].map(x=>x.toString(16).padStart(2,'0')).join('')}
function parseCookies(request){const raw=request.headers.get('cookie')||'';return Object.fromEntries(raw.split(';').map(x=>x.trim().split('=').map(decodeURIComponent)).filter(x=>x.length===2))}
function sessionCookie(token,maxAge=SESSION_DAYS*86400){return`ot_session=${encodeURIComponent(token)}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${maxAge}`}
async function createSession(env,userId){const token=randomToken(),tokenHash=await sha256(token),expires=new Date(Date.now()+SESSION_DAYS*86400000).toISOString();await env.DB.prepare('INSERT INTO sessions (user_id,token_hash,expires_at) VALUES (?,?,?)').bind(userId,tokenHash,expires).run();return token}
async function currentUser(request,env){const token=parseCookies(request).ot_session;if(!token)return null;const tokenHash=await sha256(token);const user=await env.DB.prepare(`SELECT u.id,u.name,u.phone,u.city,u.role FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>datetime('now')`).bind(tokenHash).first();return user||null}
async function requireUser(request,env){const u=await currentUser(request,env);if(!u)throw new HttpError(401,'Entre na sua conta para continuar.');return u}
async function requireAdmin(request,env){const u=await requireUser(request,env);if(u.role!=='admin')throw new HttpError(403,'Acesso restrito ao administrador.');return u}
class HttpError extends Error{constructor(status,message){super(message);this.status=status}}
async function safe(fn){try{return await fn()}catch(e){if(e instanceof HttpError)return json({error:e.message},e.status);return json({error:e.message||'Não foi possível concluir.'},400)}}
async function register(request,env){return safe(async()=>{const b=await bodyJson(request),name=cleanText(b.name,100),phone=normalizePhone(b.phone),city=cleanText(b.city,70),password=validatePassword(b.password);if(name.length<3)throw new Error('Informe seu nome completo.');if(city.length<2)throw new Error('Informe sua cidade.');const exists=await env.DB.prepare('SELECT id FROM users WHERE phone=?').bind(phone).first();if(exists)throw new Error('Já existe uma conta com este WhatsApp.');const hp=await hashPassword(password);const role=env.ADMIN_PHONE&&normalizePhone(env.ADMIN_PHONE)===phone?'admin':'user';const r=await env.DB.prepare('INSERT INTO users (name,phone,city,password_hash,password_salt,role) VALUES (?,?,?,?,?,?)').bind(name,phone,city,hp.hash,hp.salt,role).run();const id=r.meta.last_row_id,token=await createSession(env,id);return json({user:{id,name,phone,city,role}},201,{'set-cookie':sessionCookie(token)})})}
async function login(request,env){return safe(async()=>{const b=await bodyJson(request),phone=normalizePhone(b.phone),password=validatePassword(b.password);const u=await env.DB.prepare('SELECT id,name,phone,city,role,password_hash,password_salt FROM users WHERE phone=?').bind(phone).first();if(!u||!(await verifyPassword(password,u.password_salt,u.password_hash)))throw new HttpError(401,'WhatsApp ou senha incorretos.');const token=await createSession(env,u.id);return json({user:{id:u.id,name:u.name,phone:u.phone,city:u.city,role:u.role}},200,{'set-cookie':sessionCookie(token)})})}
async function logout(request,env){return safe(async()=>{const token=parseCookies(request).ot_session;if(token){const h=await sha256(token);await env.DB.prepare('DELETE FROM sessions WHERE token_hash=?').bind(h).run()}return json({ok:true},200,{'set-cookie':sessionCookie('',0)})})}
async function me(request,env){const user=await currentUser(request,env);return json({user})}
async function changePassword(request,env){return safe(async()=>{const u=await requireUser(request,env),b=await bodyJson(request),current=validatePassword(b.currentPassword),next=validatePassword(b.newPassword);const row=await env.DB.prepare('SELECT password_hash,password_salt FROM users WHERE id=?').bind(u.id).first();if(!(await verifyPassword(current,row.password_salt,row.password_hash)))throw new Error('A senha atual está incorreta.');const hp=await hashPassword(next);await env.DB.prepare('UPDATE users SET password_hash=?,password_salt=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(hp.hash,hp.salt,u.id).run();await env.DB.prepare('DELETE FROM sessions WHERE user_id=?').bind(u.id).run();const token=await createSession(env,u.id);return json({ok:true},200,{'set-cookie':sessionCookie(token)})})}
async function recoveryRequest(request,env){return safe(async()=>{const b=await bodyJson(request);let phone;try{phone=normalizePhone(b.phone)}catch{return json({ok:true})}const user=await env.DB.prepare('SELECT id FROM users WHERE phone=?').bind(phone).first();if(user){const existing=await env.DB.prepare("SELECT id FROM recovery_requests WHERE user_id=? AND status='pending' AND created_at>datetime('now','-1 day')").bind(user.id).first();if(!existing)await env.DB.prepare('INSERT INTO recovery_requests (user_id,status) VALUES (?,?)').bind(user.id,'pending').run()}return json({ok:true})})}
async function uploadImage(form,env){const file=form.get('image');if(!file||typeof file==='string'||file.size===0)return null;if(!env.MEDIA)throw new Error('O armazenamento de imagens ainda não foi configurado.');if(file.size>MAX_IMAGE)throw new Error('A imagem deve ter no máximo 5 MB.');if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw new Error('Use imagem JPG, PNG ou WebP.');const ext={'image/jpeg':'jpg','image/png':'png','image/webp':'webp'}[file.type],key=`uploads/${new Date().toISOString().slice(0,10)}/${crypto.randomUUID()}.${ext}`;await env.MEDIA.put(key,file.stream(),{httpMetadata:{contentType:file.type,cacheControl:'public, max-age=31536000, immutable'}});return`/media/${key}`}
async function createListing(request,env){return safe(async()=>{const u=await requireUser(request,env),f=await request.formData(),title=cleanText(f.get('title'),90),category=cleanText(f.get('category'),50),condition=cleanText(f.get('condition'),20),city=cleanText(f.get('city'),70),description=cleanText(f.get('description'),1000),price=Number(f.get('price'));if(title.length<3||!category||!condition||!city||description.length<10)throw new Error('Preencha todos os campos do anúncio.');if(!Number.isFinite(price)||price<0||price>99999999)throw new Error('Preço inválido.');const image=await uploadImage(f,env);await env.DB.prepare('INSERT INTO listings (user_id,title,category,price,condition_text,city,description,image_url,status) VALUES (?,?,?,?,?,?,?,?,?)').bind(u.id,title,category,price,condition,city,description,image,'pending').run();return json({ok:true},201)})}
async function createBusiness(request,env){return safe(async()=>{const u=await requireUser(request,env),f=await request.formData(),name=cleanText(f.get('name'),100),type=cleanText(f.get('type'),20),category=cleanText(f.get('category'),50),city=cleanText(f.get('city'),70),address=cleanText(f.get('address'),160),hours=cleanText(f.get('hours'),100),description=cleanText(f.get('description'),800);if(name.length<2||!['business','professional'].includes(type)||!category||!city||!address||description.length<10)throw new Error('Preencha todos os campos obrigatórios.');const image=await uploadImage(f,env);await env.DB.prepare('INSERT INTO businesses (user_id,kind,name,category,city,address,hours,description,image_url,status) VALUES (?,?,?,?,?,?,?,?,?,?)').bind(u.id,type,name,category,city,address,hours,description,image,'pending').run();return json({ok:true},201)})}
async function serveMedia(url,env){if(!env.MEDIA)return new Response('Not found',{status:404});const key=decodeURIComponent(url.pathname.slice('/media/'.length));if(!key||key.includes('..'))return new Response('Not found',{status:404});const object=await env.MEDIA.get(key);if(!object)return new Response('Not found',{status:404});const h=new Headers();object.writeHttpMetadata(h);h.set('etag',object.httpEtag);h.set('x-content-type-options','nosniff');return new Response(object.body,{headers:h})}
async function catalog(env,url){return safe(async()=>{const q=cleanText(url.searchParams.get('q'),80),city=cleanText(url.searchParams.get('city'),70);const like=`%${q}%`,cityLike=`%${city}%`;const businesses=await env.DB.prepare(`SELECT b.id,b.kind,b.name,b.category,b.city,b.address,b.hours,b.description,b.image_url,b.featured,b.rating,u.phone FROM businesses b JOIN users u ON u.id=b.user_id WHERE b.status='published' AND (?='' OR b.name LIKE ? OR b.category LIKE ? OR b.description LIKE ?) AND (?='' OR b.city LIKE ?) ORDER BY b.featured DESC,b.created_at DESC LIMIT 60`).bind(q,like,like,like,city,cityLike).all();const listings=await env.DB.prepare(`SELECT l.id,l.title,l.category,l.price,l.condition_text AS condition,l.city,l.description,l.image_url,u.phone FROM listings l JOIN users u ON u.id=l.user_id WHERE l.status='published' AND (?='' OR l.title LIKE ? OR l.category LIKE ? OR l.description LIKE ?) AND (?='' OR l.city LIKE ?) ORDER BY l.created_at DESC LIMIT 80`).bind(q,like,like,like,city,cityLike).all();return json({businesses:businesses.results,listings:listings.results})})}
async function mySummary(request,env){return safe(async()=>{const u=await requireUser(request,env);const [l,b,f]=await Promise.all([env.DB.prepare('SELECT id,title,status,price FROM listings WHERE user_id=? ORDER BY created_at DESC LIMIT 20').bind(u.id).all(),env.DB.prepare('SELECT id,name,status,category FROM businesses WHERE user_id=? ORDER BY created_at DESC LIMIT 20').bind(u.id).all(),env.DB.prepare('SELECT id FROM favorites WHERE user_id=? LIMIT 100').bind(u.id).all()]);return json({listings:l.results,businesses:b.results,favorites:f.results})})}
async function myListings(request,env){return safe(async()=>{const u=await requireUser(request,env),r=await env.DB.prepare('SELECT id,title,status,price,category,city,created_at FROM listings WHERE user_id=? ORDER BY created_at DESC').bind(u.id).all();return json({items:r.results})})}
async function myBusinesses(request,env){return safe(async()=>{const u=await requireUser(request,env),r=await env.DB.prepare('SELECT id,name,status,category,city,created_at FROM businesses WHERE user_id=? ORDER BY created_at DESC').bind(u.id).all();return json({items:r.results})})}
async function favorites(request,env){return safe(async()=>{const u=await requireUser(request,env);const r=await env.DB.prepare(`SELECT f.id,f.kind,f.item_id,COALESCE(l.title,b.name) AS name,COALESCE(l.category,b.category) AS category FROM favorites f LEFT JOIN listings l ON f.kind='listing' AND l.id=f.item_id LEFT JOIN businesses b ON f.kind='business' AND b.id=f.item_id WHERE f.user_id=? ORDER BY f.created_at DESC`).bind(u.id).all();return json({items:r.results})})}
async function toggleFavorite(request,env){return safe(async()=>{const u=await requireUser(request,env),b=await bodyJson(request),kind=cleanText(b.kind,20),id=Number(b.id);if(!['listing','business'].includes(kind)||!Number.isInteger(id))throw new Error('Favorito inválido.');const ex=await env.DB.prepare('SELECT id FROM favorites WHERE user_id=? AND kind=? AND item_id=?').bind(u.id,kind,id).first();if(ex){await env.DB.prepare('DELETE FROM favorites WHERE id=?').bind(ex.id).run();return json({favorite:false})}await env.DB.prepare('INSERT INTO favorites (user_id,kind,item_id) VALUES (?,?,?)').bind(u.id,kind,id).run();return json({favorite:true})})}
async function adminPending(request,env){return safe(async()=>{await requireAdmin(request,env);const [l,b,r]=await Promise.all([env.DB.prepare(`SELECT l.id,l.title,l.price,l.city,l.created_at,u.name AS owner FROM listings l JOIN users u ON u.id=l.user_id WHERE l.status='pending' ORDER BY l.created_at`).all(),env.DB.prepare(`SELECT b.id,b.name,b.category,b.city,b.created_at,u.name AS owner FROM businesses b JOIN users u ON u.id=b.user_id WHERE b.status='pending' ORDER BY b.created_at`).all(),env.DB.prepare(`SELECT rr.id,rr.created_at,u.name,u.phone FROM recovery_requests rr JOIN users u ON u.id=rr.user_id WHERE rr.status='pending' ORDER BY rr.created_at`).all()]);return json({listings:l.results,businesses:b.results,recoveries:r.results})})}
async function adminModerate(request,env){return safe(async()=>{await requireAdmin(request,env);const b=await bodyJson(request),action=cleanText(b.action,10),kind=cleanText(b.kind,20),id=Number(b.id);if(!['approve','reject'].includes(action)||!['listing','business'].includes(kind)||!Number.isInteger(id))throw new Error('Ação inválida.');const table=kind==='listing'?'listings':'businesses',status=action==='approve'?'published':'rejected';await env.DB.prepare(`UPDATE ${table} SET status=?,reviewed_at=CURRENT_TIMESTAMP WHERE id=? AND status='pending'`).bind(status,id).run();return json({ok:true})})}
async function adminRecoveryReset(request,env){return safe(async()=>{await requireAdmin(request,env);const b=await bodyJson(request),id=Number(b.id);if(!Number.isInteger(id))throw new Error('Solicitação inválida.');const req=await env.DB.prepare(`SELECT rr.id,rr.user_id,u.phone FROM recovery_requests rr JOIN users u ON u.id=rr.user_id WHERE rr.id=? AND rr.status='pending'`).bind(id).first();if(!req)throw new Error('Solicitação não encontrada.');const temporary=`Ot!${randomToken(5)}`;const hp=await hashPassword(temporary);await env.DB.batch([env.DB.prepare('UPDATE users SET password_hash=?,password_salt=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(hp.hash,hp.salt,req.user_id),env.DB.prepare('DELETE FROM sessions WHERE user_id=?').bind(req.user_id),env.DB.prepare("UPDATE recovery_requests SET status='resolved',resolved_at=CURRENT_TIMESTAMP WHERE id=?").bind(id)]);return json({temporaryPassword:temporary,phone:req.phone})})}